### ISSUE TITLE
Setting hover transitions on <img> element fail b/c of inline opacity transition style

### ISSUE THREAD

**Issue by amdixon** [dixonandmoe/tessarray#13]
Tessarray sets an inline style for opacity transition on the `<img>` tag (fading the images in when they've loaded). That works perfect for the loading but breaks any hover transitions applied directly to the image since the inline style overrides CSS styles in the stylesheet. Is there any way we could move that inline opacity styling to the CSS stylesheet, or apply the opacity change using JS only? Or remove it once the load sequence has finished? (this might be janky tho if someone hovers before all the images have loaded). Perhaps we can remove it on each individual image after it loads.

**Comment by markjanzer** [comment]
I just pushed up some changes. I am now setting style.opacity = "" rather than "1", and it seems to have the same effect while removing the inline opacity. I also remove the transition immediately after calling opacity = "", yet the transition still completes. Let me know if it still doesn't work!
