### ISSUE TITLE
Scoping Tessarray to use only image selectors inside of specified container class

### ISSUE THREAD

**Issue by amdixon** [dixonandmoe/tessarray#4]
If there are multiple box items with the same class name on a page Tessarray gets greedy and tries to rule them all. An example:
On the homepage I have a grid of projects, a grid of people and a grid of news items. They are all structured with the same HTML and classes, but with different container names, one is called "grid-tessarray" and the others are called "grid-normal". However, each grid's children all have the same class, "box". I only want Tessarray to be enabled on the grid with the "grid-tessarray" class, however because the other grids have the same child item/box class Tessarray justifies all the grids.

**Comment by markjanzer** [comment]
I just pushed some changes that should fix that. Now Tessarray will only look for boxes inside of the container if the container class is given. Let me know if it works!
